# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    avoid_classes_with_only_static_members: false
    constant_identifier_names: true
    prefer_relative_imports: true
analyzer:
  exclude:
    - '**/*.g.dart'
