name: flutter_sample_isar
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.0.0-dev.0
  isar_flutter_libs: ^3.0.0-dev.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.0.0-dev.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
