name: flutter_sample_isar
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.0.0-dev.15
  isar_flutter_libs: ^3.0.0-dev.15
  path_provider: ^2.0.11

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.0-dev.15
  mocktail: ^0.3.0
  pedantic_mono: ^1.20.0

flutter:
  assets:
    - assets/json/
  uses-material-design: true
